### ISSUE TITLE
Support overriding height

### ISSUE THREAD

**Issue by gaearon** [kevin940726/remark-codesandbox#17]
Height appears hardcoded:

https://github.com/kevin940726/remark-codesandbox/blob/3aa704809e40d02676ff1ec840e4c370567d7487/packages/remark-codesandbox/src/index.js#L184

Would be nice if this was a query option.

**Comment by kevin940726** [comment]
Good call! Perhaps adding it as a query param `style` instead? So that all the default styles can be overridden either globally or locally inline.

````
```js codesandbox=react?style=height:600px
```
````

If we need more customization, we can always use the `meta` mode and [generate the iframe tag ourselves](https://github.com/kevin940726/kaihao.dev/blob/2fa39dce646ac41c902561becfc7b5ebdea1bd2b/src/components/Highlight.js#L135).

I'll be working on a PR for this. I'm also happy to help integrate it with whatever project you're working on! :)

**Comment by kevin940726** [comment]
Released `v0.10.0`! Please give it a try :)
