### ISSUE TITLE
[Sugestion] - Remark CSB for NextJS

### ISSUE THREAD

**Issue by washingtonsoares** [kevin940726/remark-codesandbox#19]
Hello!

What do you think about a version for NextJS ? Do you have any plan about it ?

**Comment by kevin940726** [comment]
I've never tried Next.js yet. But as long as Next.js uses `remark` and can be configurable, it should be fairly easy to integrate `remark-codesandbox` with it.

Taking the [official doc](https://nextjs.org/docs/migrating/from-gatsby#data-fetching) here describing migrating from Gatsby to Next.js for instance, it uses `remark` directly, so it should be possible to just plug in `remark-codesandbox` there.

```diff
  const markdown = await remark()
    .use(html)
+	.use(codesandbox, { mode: 'button' })
    .process(post.content || '')
```

Might want to also remember to pass `vfile` instance instead of string literal here so that it can gets the relative file path.
