### ISSUE TITLE
customTemplate options not being applied

### ISSUE THREAD

**Issue by garethx** [kevin940726/remark-codesandbox#5]
Do you know why my customTemplates options aren't being applied in this example app? I'm trying to override the dependency version of the linked template but must have missed something in the docs

https://codesandbox.io/s/remark-codesandbox-demo-v6nuh?file=/src/index.js

**Comment by kevin940726** [comment]
The first problem here is that you are still using the original sandbox in the markdown file:

https://codesandbox.io/s/remark-codesandbox-demo-v6nuh?file=/src/index.md:47-52

While it should be `simple-node` that you just created.

But you will soon discover another problem where the contents of your `package.json` got overridden. That's because `remark-codesandbox` doesn't perform any merging algorithm, it only override the whole contents. I know it's a little bit inconvenient, but I don't have other idea for now 😞.

In `reaviz`, we merge the contents by just importing the original one:

https://github.com/jask-oss/reaviz/blob/55e12d040fa2a4f361acd369e077a72f94f6a465/.storybook/webpack.config.js#L67-L76

Unfortunately, it's not gonna work with sandboxes that are not version controlled in the same codebase.

**Comment by garethx** [comment]
Ah, I see! Thanks for clarifying how it works.
